### ISSUE TITLE
Unclear usage of initialize() and reset()

### ISSUE THREAD

**Issue by tomtargosz** [Survicate/react-native-survicate#27]
Could the docs be updated to explain how to properly use `Survicate.initialize()` and `Survicate.reset()`? I'm operating under the assumption that `initialize()` should be called when a user logs in and `reset()` when a user logs out but I'm not sure if that's correct. Additionally, the surveys still show up as expected even when `Survicate.initialize()` is never called. Is this an accepted practice or could it lead to unexpected behavior?

Update: It looks like `reset()` should be used to clear out a user's data, only for testing. https://developers.survicate.com/mobile-sdk/ios/#reseting-user-data-for-testing-purposes

**Comment by sergey-duzhych** [comment]
Hi @tomtargosz , thank you for your question! We are planning to update the documentation soon and provide more details about `Survicate.initialize()`

`Survicate.initialize()` should be used only once when the app starts, not when the user logs in.
[reset() method](https://developers.survicate.com/mobile-sdk/ios/#reseting-user-data-for-testing-purposes) is usually used for testing purposes to reset all user data stored on your device (survey views, attributes, and information about answered surveys for the targeting engine). It shouldn't be used when a user logs out of the application.

**Comment by tomtargosz** [comment]
Thank you for the response @sergey-duzhych! I noticed that my surveys are popping up and results being recorded as expected even if I'm not calling `Survicate.initialize()`- is it a requirement to call it when the app starts?

**Comment by sergey-duzhych** [comment]
Hi @tomtargosz  In order to have correctly working and behaving Survicate SDK calling the `Survicate.initialize()` method is a mandatory thing, otherwise SDK might behave in an unpredicted way.

Ifyou observe a situation in which surveys pop-up and answers are recorded without calling earlier the `Survicate.initialize()` than we need more info:

- workspace id and survey id - you can find these in the link of the survey from your Survicate panel: workspace id comes after w/ and survey id comes after surveys/

- version of the iOS SDK you are using

- snippets of code in which the app triggers SDK events or sets user traits - if those are applicable for the case.
You can send this data to me directly: sergey@survicate.com
